name: Run CMD on Windows

on: [push]

jobs:
  run-cmd:
    runs-on: windows-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run CMD Command
        run: |
          echo Hello from Windows CMD
          dir
